Create procedure sp_InsertarCliente
@IdCliente int output,
@Socio varchar(100),
@Nombre varchar(100),
@IdTipoPersona int,
@RfcFisica varchar(20),
@CurpFisica varchar(20),
@CalleFisica varchar(30),
@NumeroFisica varchar(10),
@IdEstadoFisica int,
@IdMunicipioFisica int,
@ColoniaFisica varchar(50),
@CelularFisica varchar(15),
@TelefonoFisica varchar(15),
@CorreoFisica varchar(50),
@ApoderadoFisica varchar(50),
@FolioActa varchar(30),
@IdEstadoActa int,
@FechaActa datetime,
@NotarioActa varchar(30),
@RegistroPublicoActa varchar(30),
@NumeroActa varchar(30),
@LibroActa varchar(30),
@FolioMercantil varchar(30),
@RfcApoderado varchar(20),
@CurpApoderado varchar(20),
@IneApoderado varchar(20),
@CalleApoderado varchar(30),
@IdEstadoApoderado int,
@IdMunicipioApoderado int,
@TelefonoApoderado varchar(15),
@CelularApoderado varchar(15),
@CorreoApoderado varchar(50),
@IdEstadoMovilizacion int,
@IdMunicipioMovilizacion int,
@Certificado varchar(30),
@Superficie float,
@Predio varchar(30),
@IdCuentaDe int,
@IdUsuarioCreacion int,
@FechaCreacion datetime,
@IdEstatus int
as
begin
set nocount on
merge [dbo].[Clientes] as target
using (select @IdCliente,
              @Socio,
			  @Nombre,
			  @IdTipoPersona,
			  @RfcFisica,
			  @CurpFisica,
			  @CalleFisica,
			  @NumeroFisica,
			  @IdEstadoFisica,
			  @IdMunicipioFisica,
			  @ColoniaFisica,
			  @CelularFisica,
			  @TelefonoFisica,
			  @CorreoFisica,
			  @ApoderadoFisica,
			  @FolioActa,
			  @IdEstadoActa,
			  @FechaActa,
			  @NotarioActa,
			  @RegistroPublicoActa,
			  @NumeroActa,
			  @LibroActa,
			  @FolioMercantil,
			  @RfcApoderado,
			  @CurpApoderado,
			  @IneApoderado,
			  @CalleApoderado,
			  @IdEstadoApoderado,
			  @IdMunicipioApoderado,
			  @TelefonoApoderado,
			  @CelularApoderado,
			  @CorreoApoderado,
			  @IdEstadoMovilizacion,
			  @IdMunicipioMovilizacion,
			  @Certificado,
			  @Superficie,
			  @Predio,
			  @IdCuentaDe,
			  @IdUsuarioCreacion,
			  @FechaCreacion,
			  @IdEstatus) AS SOURCE 
			  (IdCliente,
			  Socio,
			  Nombre,
			  IdTipoPersona,
			  RfcFisica,
			  CurpFisica,
			  CalleFisica,
			  NumeroFisica,
			  IdEstadoFisica,
			  IdMunicipioFisica,
			  ColoniaFisica,
			  CelularFisica,
			  TelefonoFisica,
			  CorreoFisica,
			  ApoderadoFisica,
			  FolioActa,
			  IdEstadoActa,
			  FechaActa,
			  NotarioActa,
			  RegistroPublicoActa,
			  NumeroActa,
			  LibroActa,
			  FolioMercantil,
			  RfcApoderado,
			  CurpApoderado,
			  IneApoderado,
			  CalleApoderado,
			  IdEstadoApoderado,
			  IdMunicipioApoderado,
			  TelefonoApoderado,
			  CelularApoderado,
			  CorreoApoderado,
			  IdEstadoMovilizacion,
			  IdMunicipioMovilizacion,
			  Certificado,
			  Superficie,
			  Predio,
			  IdCuentaDe,
			  IdUsuarioCreacion,
			  FechaCreacion,
			  IdEstatus)
ON (target.IdCliente = SOURCE.IdCliente)
WHEN MATCHED THEN
UPDATE SET Socio = source.Socio,
		   Nombre = source.Nombre,
		   IdTipoPersona = source.IdTipoPersona,
		   RfCFisica = source.RfcFisica,
		   CurpFisica = source.CurpFisica,
		   CalleFisica = source.CalleFisica,
		   NumeroFisica = source.NumeroFisica,
		   IdEstadoFisica = source.IdEstadoFisica,
		   IdMunicipioFisica = source.IdMunicipioFisica,
		   ColoniaFisica = source.ColoniaFisica,
		   CelularFisica = source.CelularFisica,
           TelefonoFisica = source.TelefonoFisica,
		   CorreoFisica = source.CorreoFisica,
		   ApoderadoFisica = source.ApoderadoFisica,
		   FolioActa = source.FolioActa,
		   IdEstadoActa = source.IdEstadoActa,
		   FechaActa = source.FechaActa,
		   NotarioActa = source.NotarioActa,
		   RegistroPublicoActa = source.RegistroPublicoActa,
		   NumeroActa = source.NumeroActa,
		   LibroActa = source.LibroActa,
		   FolioMercantil = source.FolioMercantil,
		   RfcApoderado = source.RfcApoderado,
		   CurpApoderado = source.CurpApoderado,
		   IneApoderado = source.IneApoderado,
		   CalleApoderado = source.CalleApoderado,
		   IdEstadoApoderado = source.IdEstadoApoderado,
		   IdMunicipioApoderado = source.IdMunicipioApoderado,
		   TelefonoApoderado = source.TelefonoApoderado,
		   CelularApoderado = source.CelularApoderado,
		   CorreoApoderado = source.CorreoApoderado,
		   IdEstadoMovilizacion = source.IdEstadoMovilizacion,
		   IdMunicipioMovilizacion = source.IdMunicipioMovilizacion,
		   Certificado = source.Certificado,
		   Superficie = source.Superficie,
		   Predio = source.Predio,
		   IdCuentaDe = source.IdCuentaDe,
		   IdUsuarioCreacion = source.IdUsuarioCreacion,
		   FechaCreacion = source.FechaCreacion,
		   IdEstatus = source.IdEstatus
WHEN NOT MATCHED THEN
INSERT (Socio,
		Nombre,
		IdTipoPersona,
		RfcFisica,
		CurpFisica,
		CalleFisica,
		NumeroFisica,
		IdEstadoFisica,
		IdMunicipioFisica,
		ColoniaFisica,
		CelularFisica,
		TelefonoFisica,
		CorreoFisica,
		ApoderadoFisica,
		FolioActa,
		IdEstadoActa,
		FechaActa,
		NotarioActa,
		RegistroPublicoActa,
		NumeroActa,
		LibroActa,
		FolioMercantil,
		RfcApoderado,
		CurpApoderado,
		IneApoderado,
		CalleApoderado,
		IdEstadoApoderado,
		IdMunicipioApoderado,
		TelefonoApoderado,
		CelularApoderado,
		CorreoApoderado,
		IdEstadoMovilizacion,
		IdMunicipioMovilizacion,
		Certificado,
		Superficie,
		Predio,
		IdCuentaDe,
		IdUsuarioCreacion,
		FechaCreacion,
		IdEstatus)
        VALUES (source.Socio,
				source.Nombre,
				source.IdTipoPersona,
				source.RfcFisica,
				source.CurpFisica,
				source.CalleFisica,
				source.NumeroFisica,
				source.IdEstadoFisica,
				source.IdMunicipioFisica,
				source.ColoniaFisica,
				source.CelularFisica,
				source.TelefonoFisica,
				source.CorreoFisica,
				source.ApoderadoFisica,
				source.FolioActa,
				source.IdEstadoActa,
				source.FechaActa,
				source.NotarioActa,
				source.RegistroPublicoActa,
				source.NumeroActa,
				source.LibroActa,
				source.FolioMercantil,
				source.RfcApoderado,
				source.CurpApoderado,
				source.IneApoderado,
				source.CalleApoderado,
				source.IdEstadoApoderado,
				source.IdMunicipioApoderado,
				source.TelefonoApoderado,
				source.CelularApoderado,
				source.CorreoApoderado,
				source.IdEstadoMovilizacion,
				source.IdMunicipioMovilizacion,
				source.Certificado,
				source.Superficie,
				source.Predio,
				source.IdCuentaDe,
				source.IdUsuarioCreacion,
				source.FechaCreacion,
				source.IdEstatus);
		SET @IdCliente = SCOPE_IDENTITY()
END
RETURN @IdCliente
