alter procedure sp_InsertarProduccionDetalle
@IdProduccionDetalle int,
@IdProduccion int,
@IdOrdenTrabajo int,
@IdPlantaOrigen int,
@FolioCIA int,
@Tipo varchar(15),
@Kilos float,
@BandExiste bit,
@IdTurno int,
@IdEstatus int,
@Fecha datetime,
@IdBaja int,
@FechaBaja datetime,
@ClaveClasificacion int,
@Micros float,
@Castigo float,
@CastigoMicCpa float,
@CastigoMicVta float,
@CastigoLargoFibra float,
@CastigoLargoFibraCpa float,
@CastigoLargoFibraVta float,
@CastigoResistenciaFibra float,
@CastigoResistenciaFibraCpa float,
@CastigoResistenciaFibraVta float,
@ClaveClasificacionCpa float,
@ClaveClasificacionVta float,
@FechaClasificacion datetime,
@Libras float,
@ClaveCertificado int,
@ClaveContratoAlgodon int,
@ClaveContratoAlgodon2 int,
@ClavePaqueteHVI int,
@LargoFibra float,
@ResistenciaFibra float
as
begin
set nocount on
merge [dbo].[ProduccionDetalle] as target
using (select 
@IdProduccionDetalle,
@IdProduccion,
@IdOrdenTrabajo,
@IdPlantaOrigen,
@FolioCIA,
@Tipo,
@Kilos,
@BandExiste,
@IdTurno,
@IdEstatus,
@Fecha,
@IdBaja,
@FechaBaja,
@ClaveClasificacion,
@Micros,
@Castigo,
@CastigoMicCpa,
@CastigoMicVta,
@CastigoLargoFibra,
@CastigoLargoFibraCpa,
@CastigoLargoFibraVta,
@CastigoResistenciaFibra,
@CastigoResistenciaFibraCpa,
@CastigoResistenciaFibraVta,
@ClaveClasificacionCpa,
@ClaveClasificacionVta,
@FechaClasificacion,
@Libras,
@ClaveCertificado,
@ClaveContratoAlgodon,
@ClaveContratoAlgodon2,
@ClavePaqueteHVI,
@LargoFibra,
@ResistenciaFibra) as source (IdProduccionDetalle,
IdProduccion,
IdOrdenTrabajo,
IdPlantaOrigen,
FolioCIA,
Tipo,
Kilos,
BandExiste,
IdTurno,
IdEstatus,
Fecha,
IdBaja,
FechaBaja,
ClaveClasificacion,
Micros,
Castigo,
CastigoMicCpa,
CastigoMicVta,
CastigoLargoFibra,
CastigoLargoFibraCpa,
CastigoLargoFibraVta,
CastigoResistenciaFibra,
CastigoResistenciaFibraCpa,
CastigoResistenciaFibraVta,
ClaveClasificacionCpa,
ClaveClasificacionVta,
FechaClasificacion,
Libras,
ClaveCertificado,
ClaveContratoAlgodon,
ClaveContratoAlgodon2,
ClavePaqueteHVI,
LargoFibra,
ResistenciaFibra) ON (target.IdProduccionDetalle = source.IdProduccionDetalle)
WHEN MATCHED THEN
UPDATE SET 
Tipo = source.Tipo,
Kilos = source.Kilos,
BandExiste = source.BandExiste,
IdEstatus = source.IdEstatus,
Fecha = source.Fecha
WHEN NOT MATCHED THEN
INSERT (IdProduccion,
IdOrdenTrabajo,
IdPlantaOrigen,
FolioCIA,
Tipo,
Kilos,
BandExiste,
IdTurno,
IdEstatus,
Fecha,
IdBaja,
FechaBaja,
ClaveClasificacion,
Micros,
Castigo,
CastigoMicCpa,
CastigoMicVta,
CastigoLargoFibra,
CastigoLargoFibraCpa,
CastigoLargoFibraVta,
CastigoResistenciaFibra,
CastigoResistenciaFibraCpa,
CastigoResistenciaFibraVta,
ClaveClasificacionCpa,
ClaveClasificacionVta,
FechaClasificacion,
Libras,
ClaveCertificado,
ClaveContratoAlgodon,
ClaveContratoAlgodon2,
ClavePaqueteHVI,
LargoFibra,
ResistenciaFibra)
VALUES (
source.IdProduccion,
source.IdOrdenTrabajo,
source.IdPlantaOrigen,
source.FolioCIA,
source.Tipo,
source.Kilos,
source.BandExiste,
source.IdTurno,
source.IdEstatus,
source.Fecha,
source.IdBaja,
source.FechaBaja,
source.ClaveClasificacion,
source.Micros,
source.Castigo,
source.CastigoMicCpa,
source.CastigoMicVta,
source.CastigoLargoFibra,
source.CastigoLargoFibraCpa,
source.CastigoLargoFibraVta,
source.CastigoResistenciaFibra,
source.CastigoResistenciaFibraCpa,
source.CastigoResistenciaFibraVta,
source.ClaveClasificacionCpa,
source.ClaveClasificacionVta,
source.FechaClasificacion,
source.Libras,
source.ClaveCertificado,
source.ClaveContratoAlgodon,
source.ClaveContratoAlgodon2,
source.ClavePaqueteHVI,
source.LargoFibra,
source.ResistenciaFibra);
END