 insert into Municipios values ('Ahumada',6,1)
 insert into Municipios values ('Aldama',6,1)
 insert into Municipios values ('Allende',6,1)
 insert into Municipios values ('Aquiles Serdán',6,1)
 insert into Municipios values ('Ascensión',6,1)
 insert into Municipios values ('Bachíniva',6,1)
 insert into Municipios values ('Balleza',6,1)
 insert into Municipios values ('Batopilas',6,1)
 insert into Municipios values ('Bocoyna',6,1)
 insert into Municipios values ('Buenaventura',6,1)
 insert into Municipios values ('Camargo',6,1)
 insert into Municipios values ('Carichí',6,1)
 insert into Municipios values ('Casas Grandes',6,1)
 insert into Municipios values ('Chihuahua',6,1)
 insert into Municipios values ('Chínipas',6,1)
 insert into Municipios values ('Coronado',6,1)
 insert into Municipios values ('Coyame del Sotol',6,1)
 insert into Municipios values ('Cuauhtémoc',6,1)
 insert into Municipios values ('Cusihuiriachi',6,1)
 insert into Municipios values ('Delicias',6,1)
 insert into Municipios values ('Belisario Domínguez',6,1)
 insert into Municipios values ('El Tule',6,1)
 insert into Municipios values ('Galeana',6,1)
 insert into Municipios values ('Gómez Farías',6,1)
 insert into Municipios values ('Gran Morelos',6,1)
 insert into Municipios values ('Guachochi',6,1)
 insert into Municipios values ('Guadalupe',6,1)
 insert into Municipios values ('Guadalupe y Calvo',6,1)
 insert into Municipios values ('Guazapares',6,1)
 insert into Municipios values ('Guerrero',6,1)
 insert into Municipios values ('Hidalgo del Parral',6,1)
 insert into Municipios values ('Huejotitán',6,1)
 insert into Municipios values ('Ignacio Zaragoza',6,1)
 insert into Municipios values ('Janos',6,1)
 insert into Municipios values ('Jiménez',6,1)
 insert into Municipios values ('Juárez',6,1)
 insert into Municipios values ('Julimes',6,1)
 insert into Municipios values ('La Cruz',6,1)
 insert into Municipios values ('López',6,1)
 insert into Municipios values ('Madera',6,1)
 insert into Municipios values ('Maguarichi',6,1)
 insert into Municipios values ('Manuel Benavides',6,1)
 insert into Municipios values ('Matachí',6,1)
 insert into Municipios values ('Matamoros',6,1)
 insert into Municipios values ('Meoqui',6,1)
 insert into Municipios values ('Morelos',6,1)
 insert into Municipios values ('Moris',6,1)
 insert into Municipios values ('Namiquipa',6,1)
 insert into Municipios values ('Nonoava',6,1)
 insert into Municipios values ('Nuevo Casas Grandes',6,1)
 insert into Municipios values ('Ocampo',6,1)
 insert into Municipios values ('Ojinaga',6,1)
 insert into Municipios values ('Praxedis G. Guerrero',6,1)
 insert into Municipios values ('Riva Palacio',6,1)
 insert into Municipios values ('Rosales',6,1)
 insert into Municipios values ('Rosario',6,1)
 insert into Municipios values ('San Francisco de Borja',6,1)
 insert into Municipios values ('San Francisco de Conchos',6,1)
 insert into Municipios values ('San Francisco del Oro',6,1)
 insert into Municipios values ('Santa Bárbara',6,1)
 insert into Municipios values ('Santa Isabel',6,1)
 insert into Municipios values ('Satevó',6,1)
 insert into Municipios values ('Saucillo',6,1)
 insert into Municipios values ('Temósachic',6,1)
 insert into Municipios values ('Urique',6,1)
 insert into Municipios values ('Uruachi',6,1)
 insert into Municipios values ('Valle de Zaragoza',6,1)