 insert into Estados values ('Aguascalientes',1)
 insert into Estados values ('Baja California',1)
 insert into Estados values ('Baja California Sur',1)
 insert into Estados values ('Campeche',1)
 insert into Estados values ('Chiapas',1)
 insert into Estados values ('Chihuahua',1)
 insert into Estados values ('Ciudad de México',1)
 insert into Estados values ('Coahuila de Zaragoza',1)
 insert into Estados values ('Colima',1)
 insert into Estados values ('Durango',1)
 insert into Estados values ('Estado de México',1)
 insert into Estados values ('Guanajuato',1)
 insert into Estados values ('Guerrero',1)
 insert into Estados values ('Hidalgo',1)
 insert into Estados values ('Jalisco',1)
 insert into Estados values ('Michoacán de Ocampo',1)
 insert into Estados values ('Morelos',1)
 insert into Estados values ('Nayarit',1)
 insert into Estados values ('Nuevo León',1)
 insert into Estados values ('Oaxaca',1)
 insert into Estados values ('Puebla',1)
 insert into Estados values ('Querétaro',1)
 insert into Estados values ('Quintana Roo',1)
 insert into Estados values ('San Luis Potosí',1)
 insert into Estados values ('Sinaloa',1)
 insert into Estados values ('Sonora',1)
 insert into Estados values ('Tabasco',1)
 insert into Estados values ('Tamaulipas',1)
 insert into Estados values ('Tlaxcala',1)
 insert into Estados values ('Veracruz de Ignacio de la Llave',1)
 insert into Estados values ('Yucatán',1)
 insert into Estados values ('Zacatecas',1)