create table CompraPacas (
IdCompra int not null identity(1,1) primary key,
IdContratoAlgodon int not null,
IdProductor int not null,
IdPlanta int not null,
IdModalidadCompra int not null,
Fecha datetime not null,
TotalPacas int not null,
Observaciones varchar(500) not null,
CastigoMicros float not null,
CastigoLargoFibra float not null,
CastigoResistenciaFibra float not null,
TotalPesosMx float not null,
TotalDlls int not null,
InteresPesosMx float not null,
InteresDlls float not null,
PrecioQuintal Float not null,
PrecioQuintalBorregos float not null,
PrecioDolar float not null,
Descuento float not null,
Total float not null,
IdUsuarioCreacion int not null,
FechaCreacion datetime not null,
IdUsuarioActualizacion int not null,
FechaActualizacion datetime not null
)