create table ContratoVenta (
IdContratoAlgodon int not null primary key identity(1,1),
IdComprador int,
Pacas int,
PrecioQuintal float,
Puntos float,
FechaLiquidacion datetime,
Presidente varchar(100),
IdModalidadCompra int,
Temporada varchar(20),
PrecioSM float,
PrecioMP float,
PrecioM float,
PrecioSLMP float,
PrecioSLM float,
PrecioLMP float,
PrecioLM float,
PrecioSGO float,
PrecioGO float,
PrecioO float,
IdEstatus int,
IdUsuarioCreacion int,
FechaCreacion datetime,
IdUsuarioActualizacion int,
FechaActualizacion datetime
)