create table ProduccionDetalle (
IdProduccionDetalle int not null identity(1,1) primary key,
IdProduccion int not null,
IdOrdenTrabajo int not null,
IdPlantaOrigen int not null,
FolioCIA int not null,
Tipo varchar(15),
Kilos float not null,
BandExiste bit,
IdTurno int,
IdEstatus int,
Fecha datetime,
IdBaja int,
FechaBaja datetime,
ClaveClasificacion int,
Micros float,
Castigo float,
CastigoMicCpa float,
CastigoMicVta float,
CastigoLargoFibra float,
CastigoLargoFibraCpa float,
CastigoLargoFibraVta float,
CastigoResistenciaFibra float,
CastigoResistenciaFibraCpa float,
CastigoResistenciaFibraVta float,
ClaveClasificacionCpa float,
ClaveClasificacionVta float,
FechaClasificacion datetime,
Libras float,
ClaveCertificado int,
ClaveContratoAlgodon int,
ClaveContratoAlgodon2 int,
ClavePaqueteHVI int,
LargoFibra float,
ResistenciaFibra float
)