create table Produccion (
IdProduccion int not null identity(1,1) primary key,
IdPlantaOrigen int,
IdPlantaDestino int,
IdOrdenTrabajo int,
Tipo varchar(20),
IdCliente int,
Fecha datetime,
IdEstatus int,
TotalHueso float,
Pacas int,
PlumaPacas float,
PlumaBorregos float,
Pluma float,
Semilla float,
Merma float,
Borra float,
PorcentajePluma float,
PorcentajeSemilla float,
PorcentajeMerma float,
IdUsuarioCreacion int,
FechaCreacion datetime,
IdUsuarioActualizacion int,
FechaActualizacion datetime
)