Public Class Clientes
    Inherits Tarjeta
    Public IdCliente As Integer
    Public Socio As String
    Public Nombre As String
    Public IdTipoPersona As Integer
    Public RfcFisica As String
    Public CurpFisica As String
    Public CalleFisica As String
    Public NumeroFisica As String
    Public IdEstadoFisica As Integer
    Public IdMunicipioFisica As Integer
    Public ColoniaFisica As String
    Public CelularFisica As String
    Public TelefonoFisica As String
    Public CorreoFisica As String
    Public ApoderadoFisica As String
    Public FolioActa As String
    Public IdEstadoActa As Integer
    Public FechaActa As Date
    Public NotarioActa As String
    Public RegistroPublicoActa As String
    Public NumeroActa As String
    Public LibroActa As String
    Public FolioMercantial As String
    Public RfcApoderado As String
    Public CurpApoderado As String
    Public IneApoderado As String
    Public CalleApoderado As String
    Public IdEstadoApoderado As Integer
    Public IdMunicipioApoderado As Integer
    Public TelefonoApoderado As String
    Public CelularApoderado As String
    Public CorreoApoderado As String
    Public IdEstadoMovilizacion As Integer
    Public IdMunicipioMovilizacion As Integer
    Public Certificado As String
    Public Superficie As String
    Public Predio As String
    Public IdCuentaDe As Integer
    Public IdEstatus As Integer
End Class
